theme: minima
title: A Place For 航's Head
description: 一个独特的灵魂
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM


copyright: >-
  &copy; #YEAR# 航
  [MIT License](https://opensource.org/license/mit/)
