theme: jekyll-theme-minimal
title: A Place For 航's Head
description: An unique soul with curiousity
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
copyright: >-
  &copy; #YEAR# 航
  [MIT License](https://opensource.org/license/mit/)
